version: '2.1'
services:
  db:
    image: postgres:9.5.5
    networks:
      - backend
  housing-service:
    build: .
    environment:
    - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
    - DEPLOY_TARGET=${DEPLOY_TARGET}
    - CONFIG_BUCKET=${CONFIG_BUCKET}
    command: /code/start-dev-server.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
    driver: bridge
