# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affordable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affordable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HousingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReportYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='report_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_backend.ReportYear'),
        ),
        migrations.AddField(
            model_name='affordable',
            name='demographic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_backend.Demographic'),
        ),
        migrations.AddField(
            model_name='affordable',
            name='housing_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_backend.HousingSize'),
        ),
        migrations.AddField(
            model_name='affordable',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_backend.Neighborhood'),
        ),
    ]
