# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborhoodRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amt', models.IntegerField()),
                ('housing_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_backend.HousingSize')),
                ('nh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_backend.Neighborhood')),
            ],
        ),
        migrations.AddField(
            model_name='demographic',
            name='household_comp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='demographic',
            name='housing_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demographic',
            name='income_median',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demographic',
            name='per_with_children',
            field=models.IntegerField(default=0),
        ),
    ]
