# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CraigslistPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='when the record was created')),
                ('listed_on', models.DateTimeField(help_text='when the craigslist listing was posted')),
                ('rent', models.IntegerField(help_text='monthly rent')),
                ('bedrooms', models.DecimalField(decimal_places=1, help_text='number of bedrooms', max_digits=3, null=True)),
                ('bathrooms', models.DecimalField(decimal_places=1, help_text='number of bathrooms', max_digits=3, null=True)),
                ('sq_ft', models.IntegerField(help_text='square footage', null=True)),
                ('url', models.TextField(help_text='url of original listing from which this info was scraped')),
                ('title', models.TextField(help_text='original title of the listing')),
                ('lat', models.FloatField(help_text='latitude', null=True)),
                ('lon', models.FloatField(help_text='longitude', null=True)),
            ],
        ),
    ]
