# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20170208_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='craigslistposting',
            name='cl_id',
            field=models.BigIntegerField(help_text='craigslist ID of listing', null=True),
        ),
        migrations.AlterField(
            model_name='craigslistposting',
            name='listed_on',
            field=models.DateTimeField(help_text='when the craigslist listing was posted'),
        ),
    ]
