# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20170208_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craigslistposting',
            name='cl_id',
            field=models.BigIntegerField(default=69, help_text='craigslist ID of listing', unique=True),
            preserve_default=False,
        ),
    ]
